spring.application.name=demo

# 1. Cấu hình DB (Bỏ password đi cho dễ test)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# Dòng này cực kỳ quan trọng để giữ DB sống khi có kết nối từ bên ngoài
spring.datasource.generate-unique-name=false

# 2. H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Cho phép trình duyệt truy cập vào DB trong RAM
spring.h2.console.settings.web-allow-others=true

# 3. Ép chạy đúng port 8080
server.port=8080

# 4. JPA Debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create-drop